global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel:8889']
      - targets: ['otel:8888']

# scrape_configs:
#   - job_name: 'prometheus'
#     scrape_interval: 5s
#     static_configs:
#       - targets: ['localhost:9090']
#   - job_name: 'otel'
#     scrape_interval: 5s
#     static_configs:
#       - targets: ['localhost:8888']