receivers:
  otlp: 
    protocols:
      grpc:
      http:
processors:
  batch:
  memory_limiter:
    # Same as --mem-ballast-size-mib CLI argument
    ballast_size_mib: 683
    # 80% of maximum memory up to 2G
    limit_mib: 1500
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s
extensions:
  health_check: {}
  zpages: 
    endpoint: :55679
exporters:
  honeycomb:
    api_key: ""
    dataset: "rush"
    sample_rate: 25
    sample_rate_attribute: "hny.sample_rate"
    debug: true
  newrelic:
    apikey: 
    timeout: 30s
    common_attributes:
      server: rush
      ready_to_rock: true
      volume: 11
  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 5
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "default"
    const_labels:
      env: rush-dev
service:
  extensions: [health_check, zpages]
  pipelines:
    traces/1:
      receivers: [otlp]
      processors: [batch]
      exporters: [honeycomb, logging]
    metrics/1:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]