receivers:
  otlp: 
    protocols:
      grpc:
      http:
processors:
  batch:
  memory_limiter:
    # Same as --mem-ballast-size-mib CLI argument
    ballast_size_mib: 683
    # 80% of maximum memory up to 2G
    limit_mib: 1500
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s
  queued_retry:
extensions:
  health_check: {}
  zpages: 
    endpoint: "localhost:55679"
exporters:
  honeycomb:
    api_key: ""
    dataset: "rush"
    # api_url: "https://api.testhost.io"
    sample_rate: 25
    sample_rate_attribute: "hny.sample_rate"
    debug: true
  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 5
  prometheus:
    endpoint: "prometheus:9090"
    namespace: "default"
    const_labels:
      env: rush-dev
    send_timestamps: true
service:
  extensions: [health_check, zpages]
  pipelines:
    traces/1:
      receivers: [otlp]
      processors: [memory_limiter, batch, queued_retry]
      exporters: [honeycomb]
    traces/2:
      receivers: [otlp]
      processors: [memory_limiter, batch, queued_retry]
      exporters: [logging]
    metrics/1:
         receivers: [otlp]
         processors: [memory_limiter, batch, queued_retry]
         exporters: [prometheus, logging]